Repository pucmg-2023-02-lds-g1/Projeto1-matricula, pull requests merged in 2023-09, with the labels that each got.

#69 Realizar/Cancelar matricula
  implementacao/src/arquivos/arqUsuarios.txt
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code

#70 Desmatricular aluno
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code

#71 Mudanca no codigo de visualizacao
  implementacao/src/arquivos/arqUsuarios.txt
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code

#78 Mudanca de visualizar usuario de getDados para getTipo
  implementacao/src/arquivos/arqUsuarios.txt
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code

#79 correções cobrança
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaCobranca.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: bug, code

#81 pequenas correções
  implementacao/src/main/java/business/Cobranca.java
  implementacao/target/classes/business/Cobranca.class
Labels: bug, code

#82 Realizar/Cancelar matricula
  implementacao/src/main/java/business/App.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Cobranca.class
  implementacao/target/classes/business/Curso.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/IAtivada.class
  implementacao/target/classes/business/IObrigatorio.class
  implementacao/target/classes/business/ISalvavel.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/Usuario.class
  implementacao/target/classes/business/UsuarioInvalidoException.class
  implementacao/target/test-classes/business/AppTest.class
Labels: bug

#84 Correções realizar/cancelar matricula
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: bug

#88 Exceções
  implementacao/src/main/java/business/Aluno.java
  implementacao/src/main/java/business/Disciplina.java
  implementacao/src/main/java/business/Professor.java
  implementacao/src/main/java/business/Secretario.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/src/main/java/business/Usuario.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/Usuario.class
Labels: code

#90 correções 3
  implementacao/src/arquivos/arqDisciplina.txt
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: bug

#96 novas correções cobrança
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Cobranca.java
  implementacao/src/main/java/business/SistemaCobranca.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Cobranca.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: bug, code

#102 Professor lessiona disciplina
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Professor.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code

#107 Robustez
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Disciplina.java
  implementacao/src/main/java/business/DisciplinaCheiaException.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/DisciplinaCheiaException.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: bug

#108 Socorro3
  implementacao/src/arquivos/arqCobranca.txt
  implementacao/src/arquivos/arqDisciplina.txt
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Disciplina.java
  implementacao/src/main/java/business/DisciplinaCheiaException.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/DisciplinaCheiaException.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code
