Repository pucmg-2023-02-lds-g1/Projeto1-matricula, pull requests merged in 2023-08, with the labels that each got.

#7 Add files via upload
  projeto/Diagrama de Classes/SistemaDeMatriculasUML.asta
  projeto/Diagrama de Classes/SistemaMatriculaUML.png
Labels: documentation

#21 Criaçao das classes vazias(Usuario,Aluno,Secretario)
  implementacao/src/main/java/business/Aluno.java
  implementacao/src/main/java/business/Secretario.java
  implementacao/src/main/java/business/Usuario.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/Usuario.class
  implementacao/target/test-classes/business/AppTest.class
Labels: code

#22 classe SistemaMatricula
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/SistemaMatricula.class
  projeto/Diagrama de Classes/SistemaDeMatriculasUML.asta
Labels: code

#40 Login
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/src/main/java/business/Usuario.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/Usuario.class
Labels: code

#42 Secretario cria aluno/professor
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/src/main/java/business/UsuarioInvalidoException.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/UsuarioInvalidoException.class
Labels: code

#48 Cobrança em andamento
  implementacao/src/main/java/business/Aluno.java
  implementacao/src/main/java/business/SistemaCobranca.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/src/main/java/business/cobranca.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/cobranca.class
Labels: code

#49 Correções
  .vscode/settings.json
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/cobranca.class
Labels: bug

#53 Realizar matricula e cancelar matricula de aluno
  implementacao/src/main/java/business/Aluno.java
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Disciplina.java
  implementacao/src/main/java/business/Secretario.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/src/main/java/business/Usuario.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Curso.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/IAtivada.class
  implementacao/target/classes/business/IObrigatorio.class
  implementacao/target/classes/business/ISalvavel.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/Usuario.class
  implementacao/target/classes/business/UsuarioInvalidoException.class
  implementacao/target/classes/business/cobranca.class
  implementacao/target/test-classes/business/AppTest.class
Labels: code

#54 Excluir Usuario
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Curso.class
  implementacao/target/classes/business/Disciplina.class
  implementacao/target/classes/business/IAtivada.class
  implementacao/target/classes/business/IObrigatorio.class
  implementacao/target/classes/business/ISalvavel.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/SistemaCobranca.class
  implementacao/target/classes/business/SistemaMatricula.class
  implementacao/target/classes/business/Usuario.class
  implementacao/target/classes/business/UsuarioInvalidoException.class
  implementacao/target/classes/business/cobranca.class
  implementacao/target/test-classes/business/AppTest.class
Labels: code

#66 Visualizar Usuarios
  .vscode/settings.json
  implementacao/src/arquivos/arqUsuarios.txt
  implementacao/src/main/java/business/Aluno.java
  implementacao/src/main/java/business/App.java
  implementacao/src/main/java/business/Professor.java
  implementacao/src/main/java/business/Secretario.java
  implementacao/src/main/java/business/SistemaMatricula.java
  implementacao/target/classes/business/Aluno.class
  implementacao/target/classes/business/App.class
  implementacao/target/classes/business/Professor.class
  implementacao/target/classes/business/Secretario.class
  implementacao/target/classes/business/SistemaMatricula.class
Labels: code
